"use client";
import { useState, useEffect, useRef } from "react";
import { MapPin, Volume2, VolumeX, Copy, Check, Send, Camera, MessageCircle } from "lucide-react";
export default function EgresadosMigue() {
  const [timeLeft, setTimeLeft] = useState({dias:0,horas:0,minutos:0,segundos:0});
  const [rsvp, setRsvp] = useState<string|null>(null);
  const [name, setName] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [done, setDone] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [copied, setCopied] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);
  const eventDate = new Date("2025-11-15T20:00:00");
  useEffect(()=>{const a=audioRef.current;if(a){a.volume=0.6;a.play().catch(()=>{const h=()=>{audioRef.current?.play();document.removeEventListener("click",h);};document.addEventListener("click",h);});}}, []);
  useEffect(()=>{const t=setInterval(()=>{const d=eventDate.getTime()-Date.now();if(d>0)setTimeLeft({dias:Math.floor(d/86400000),horas:Math.floor((d%86400000)/3600000),minutos:Math.floor((d%3600000)/60000),segundos:Math.floor((d%60000)/1000)});},1000);return()=>clearInterval(t);}, []);
  useEffect(()=>{const o=new IntersectionObserver((es)=>{es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("vis");});},{threshold:0.1});document.querySelectorAll(".fu").forEach(el=>o.observe(el));return()=>o.disconnect();}, []);
  const sendWA=()=>{window.open(`https://wa.me/5491112345678?text=${encodeURIComponent(`Soy ${name}. ${rsvp==="si"?"Voy a la fiesta de egresados!":"No voy a poder ir."}`)}`, "_blank");setDone(true);};
  return (<div className="min-h-screen bg-[#2a2a3a] text-white overflow-hidden">
    <audio ref={audioRef} loop preload="auto"><source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3" type="audio/mpeg"/></audio>
    <div className="fixed bottom-6 left-6 z-50"><button onClick={()=>{if(audioRef.current){audioRef.current.muted=!isMuted;setIsMuted(!isMuted);}}} className={`w-11 h-11 rounded-full flex items-center justify-center shadow-lg ${isMuted?"bg-white/10 text-white/40":"bg-[#e8d44d] text-[#2a2a3a] shadow-[#e8d44d]/30"}`}>{isMuted?<VolumeX size={16}/>:<Volume2 size={16}/>}</button></div>
    <section className="relative min-h-screen flex flex-col items-center justify-center px-6 py-16">
      <div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&h=1200&fit=crop" alt="Egresados" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-[#2a2a3a]/85"></div></div>
      <div className="absolute inset-6 sm:inset-10 border-2 border-[#e8d44d] pointer-events-none"></div>
      <svg className="absolute top-12 left-12 w-8 h-8 text-[#e8d44d] opacity-70" viewBox="0 0 40 40"><line x1="20" y1="4" x2="20" y2="36" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><line x1="4" y1="20" x2="36" y2="20" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><circle cx="20" cy="20" r="2" fill="currentColor"/></svg>
      <svg className="absolute top-12 right-12 w-8 h-8 text-[#e8d44d] opacity-70" viewBox="0 0 40 40"><line x1="20" y1="4" x2="20" y2="36" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><line x1="4" y1="20" x2="36" y2="20" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><circle cx="20" cy="20" r="2" fill="currentColor"/></svg>
      <svg className="absolute bottom-12 left-12 w-8 h-8 text-[#e8d44d] opacity-70" viewBox="0 0 40 40"><line x1="20" y1="4" x2="20" y2="36" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><line x1="4" y1="20" x2="36" y2="20" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><circle cx="20" cy="20" r="2" fill="currentColor"/></svg>
      <svg className="absolute bottom-12 right-12 w-8 h-8 text-[#e8d44d] opacity-70" viewBox="0 0 40 40"><line x1="20" y1="4" x2="20" y2="36" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><line x1="4" y1="20" x2="36" y2="20" stroke="currentColor" strokeWidth="0.5" strokeDasharray="2 2"/><circle cx="20" cy="20" r="2" fill="currentColor"/></svg>
      <div className="relative z-10 text-center max-w-lg mx-auto">
        <p className="text-[#e8d44d] text-sm tracking-[0.4em] uppercase mb-4">Egresados 2025</p>
        <h1 className="font-[family-name:var(--font-playfair)] italic text-[#e8d44d] text-5xl sm:text-6xl md:text-7xl leading-tight mb-2">Fiesta de</h1>
        <h1 className="font-[family-name:var(--font-playfair)] italic text-[#e8d44d] text-5xl sm:text-6xl md:text-7xl leading-tight mb-6">egresados</h1>
        <div className="flex justify-center mb-6"><div className="w-32 border-t-2 border-dotted border-[#e8d44d]"></div></div>
        <p className="text-white/80 text-sm leading-relaxed mb-8">Nos reunimos en la casa de Migue para compartir unas cervezas y unas pizzas.</p>
        <p className="text-[#e8d44d] text-sm font-bold tracking-wider uppercase">15 de Noviembre de 2025 a las 20:00 hs.</p>
        <p className="text-white/50 text-xs mt-6 tracking-wider uppercase">Mandale un mensaje a Migue si queres mas informacion</p>
      </div>
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-bounce z-10"><div className="w-5 h-8 border border-[#e8d44d]/40 rounded-full flex items-start justify-center p-1"><div className="w-1 h-2 bg-[#e8d44d]/60 rounded-full"></div></div></div>
    </section>
    <section className="py-14 bg-[#2a2a3a] border-t border-[#e8d44d]/10 fu opacity-0 translate-y-6 transition-all duration-700"><div className="max-w-sm mx-auto px-6"><p className="text-[#e8d44d] text-xs tracking-[0.3em] uppercase text-center mb-6">Faltan</p><div className="grid grid-cols-4 gap-3">{[{v:timeLeft.dias,l:"Dias"},{v:timeLeft.horas,l:"Hrs"},{v:timeLeft.minutos,l:"Min"},{v:timeLeft.segundos,l:"Seg"}].map(i=>(<div key={i.l} className="text-center"><div className="bg-[#e8d44d]/10 border border-[#e8d44d]/20 rounded-lg p-3"><span className="text-2xl font-black text-white">{String(i.v).padStart(2,"0")}</span></div><p className="text-[#e8d44d]/50 text-[9px] uppercase mt-1">{i.l}</p></div>))}</div></div></section>
    <section className="py-14 bg-[#232333] border-t border-[#e8d44d]/10 fu opacity-0 translate-y-6 transition-all duration-700"><div className="max-w-md mx-auto px-6"><p className="text-[#e8d44d] text-xs tracking-[0.3em] uppercase text-center mb-8">Programa</p><div className="space-y-5">{[{t:"20:00",n:"Arrancamos",d:"Birra y pizza en lo de Migue"},{t:"22:00",n:"Previa",d:"Musica, juegos y fotos"},{t:"00:00",n:"Salimos",d:"Boliche o seguimos aca"},{t:"02:00",n:"After",d:"Los que sobrevivan"}].map((i,idx)=>(<div key={idx} className="flex items-start gap-4"><div className="text-right w-14 flex-shrink-0"><p className="text-[#e8d44d] font-bold text-sm">{i.t}</p></div><div className="w-px bg-[#e8d44d]/20 relative"><div className="absolute top-1 -left-[3px] w-2 h-2 rounded-full bg-[#e8d44d]"></div></div><div className="pb-3"><p className="text-white text-sm font-medium">{i.n}</p><p className="text-white/40 text-xs">{i.d}</p></div></div>))}</div></div></section>
    <section className="py-14 bg-[#2a2a3a] border-t border-[#e8d44d]/10 fu opacity-0 translate-y-6 transition-all duration-700"><div className="max-w-md mx-auto px-6 text-center"><p className="text-[#e8d44d] text-xs tracking-[0.3em] uppercase mb-4">Donde?</p><h3 className="text-white font-bold text-lg mb-1">Casa de Migue</h3><p className="text-white/40 text-xs mb-4">Barrio Los Pinos, Casa 23</p><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3284!2d-58.40!3d-34.57!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2z!5e0!3m2!1ses!2sar!4v1" width="100%" height="180" style={{border:0}} allowFullScreen loading="lazy" className="rounded-lg mb-4"></iframe><a href="https://maps.google.com" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#e8d44d] text-[#2a2a3a] text-xs font-bold uppercase rounded-full"><MapPin size={14}/> Abrir Mapa</a></div></section>
    <section className="py-16 bg-[#232333] border-t border-[#e8d44d]/10 fu opacity-0 translate-y-6 transition-all duration-700"><div className="max-w-sm mx-auto px-6 text-center"><p className="text-[#e8d44d] text-xs tracking-[0.3em] uppercase mb-3">Confirma</p><h2 className="text-white text-2xl font-black uppercase mb-6">Vas a venir?</h2>{done?(<div className="border border-[#e8d44d]/20 rounded-xl p-6"><div className="text-3xl mb-2">🎓</div><p className="text-white font-bold">Dale {name}!</p><p className="text-white/50 text-xs mt-1">{rsvp==="si"?"Te esperamos con birra fria!":"Sera la proxima!"}</p></div>):!showForm?(<div className="space-y-3"><button onClick={()=>{setRsvp("si");setShowForm(true);}} className="w-full py-4 bg-[#e8d44d] text-[#2a2a3a] font-bold text-sm uppercase rounded-full">Ahi voy! 🍕🍺</button><button onClick={()=>{setRsvp("no");setShowForm(true);}} className="w-full py-3 border border-white/20 text-white/50 text-sm uppercase rounded-full">No puedo</button></div>):(<form onSubmit={e=>{e.preventDefault();setDone(true);}} className="space-y-3 text-left"><input type="text" required value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre" className="w-full bg-white/5 border border-[#e8d44d]/20 rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-[#e8d44d]"/><div className="flex gap-2"><button type="submit" className="flex-1 py-3 bg-[#e8d44d] text-[#2a2a3a] text-xs font-bold uppercase rounded-full flex items-center justify-center gap-1"><Check size={14}/> Confirmar</button><button type="button" onClick={sendWA} className="flex-1 py-3 bg-[#25d366] text-white text-xs font-bold uppercase rounded-full flex items-center justify-center gap-1"><Send size={14}/> WhatsApp</button></div></form>)}</div></section>
    <section className="py-12 bg-[#2a2a3a] border-t border-[#e8d44d]/10 fu opacity-0 translate-y-6 transition-all duration-700"><div className="max-w-sm mx-auto px-6 text-center"><p className="text-[#e8d44d] text-xs tracking-[0.3em] uppercase mb-3">Vaquita</p><h3 className="text-white text-lg font-bold mb-4">Para la pizza y birra 🍕🍺</h3><div className="bg-[#232333] border border-[#e8d44d]/20 rounded-xl p-4"><p className="text-[9px] text-[#e8d44d] uppercase mb-1">Alias</p><div className="flex items-center justify-between bg-white/5 rounded-lg px-3 py-2"><span className="text-white text-sm font-medium">egresados.migue.2025</span><button onClick={()=>{navigator.clipboard.writeText("egresados.migue.2025");setCopied(true);setTimeout(()=>setCopied(false),2000);}} className="text-[#e8d44d] flex items-center gap-1 text-xs">{copied?<Check size={14}/>:<Copy size={14}/>}{copied?"Listo!":"Copiar"}</button></div></div></div></section>
    <section className="py-10 bg-[#232333] text-center border-t border-[#e8d44d]/10"><p className="text-[#e8d44d] font-[family-name:var(--font-playfair)] italic text-2xl">Egresados 2025</p><p className="text-white/40 text-xs mt-2">Casa de Migue &bull; 15.11.2025</p><p className="text-white/20 text-[9px] mt-6 tracking-wider">HECHO CON AMOR POR <span className="text-[#e8d44d]/50">TE INVITO APP</span></p></section>
    <style jsx global>{`.fu{opacity:0;transform:translateY(24px);transition:opacity .7s,transform .7s}.vis{opacity:1!important;transform:translateY(0)!important}`}</style>
  </div>);
}
